import './Main.scss';

export function Main() {
  return (
    <main id="main">
      First Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Main Content Here<br />
      Last Main Content Here<br />
    </main>
  );
}